In [1]:
import numpy as np

## ★array에 sigmoid같은 함수를 씌우면 모든 원소에 적용된다.

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


def sigmoid(z):
    return 1/(1+np.e**(-z))

sigmoid(a)

array([[0.73105858, 0.88079708, 0.95257413],
       [0.98201379, 0.99330715, 0.99752738],
       [0.99908895, 0.99966465, 0.99987661]])

## ★Broadcasting
- 코드를 짧게 만들어주는 역할을 함.
- (m,n)mat가 있을 때, 행 벡터나 열벡터를 복사해서 (m,n)mat과 계산할 수 있다.


### 예1)  
Calories from Carbs, Proteins, Fats in 100g of different foods:
![foodmat](../image/foodmat.PNG)

In [8]:
# 각각의 음식에서 영양소가 몇 %를 차지하는지 계산하기
# -- 열벡터 각각의 값을 더해서 열벡터를 나누면 됨
# -- for문 쓰면 안 됨

A = np.array([[56, 0, 4.4, 68],
              [1.2, 104, 52, 8],
              [1.8, 135, 99, 0.9]])

cal = A.sum(axis=0) # 열벡터의 합

## ★Broadcasting
# (3x4 mat) / (1x4 mat)
pct = A/(cal.reshape(1, 4)) * 100  # 차원이 확실하지 않을 땐 reshape을 사용 (O(1))
                                   
print(pct)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### 예2) 
vector + 상수 → vector + vector

In [12]:
colvec = np.array([[1, 2, 3, 4]]).reshape(4, 1)
print(colvec)
print('-'*5)
print(colvec + 100)

[[1]
 [2]
 [3]
 [4]]
-----
[[101]
 [102]
 [103]
 [104]]


### 예3)

(m,n) mat + (1,n) mat → (m,n) mat + (m,n) mat

In [13]:
mn_mat = np.array([[1, 2, 3], [4, 5, 6]])
n_mat = np.array([[100, 200, 300]])
print(mn_mat + n_mat)

[[101 202 303]
 [104 205 306]]


### 예4)
(m,n) mat + (m,1) mat → (m,n) mat + (m,n) mat

In [14]:
mn_mat = np.array([[1, 2, 3], [4, 5, 6]])
m1_mat = np.array([[100, 200]]).reshape(2, 1)
print(mn_mat + m1_mat)

[[101 102 103]
 [204 205 206]]
